#!/bin/bash

IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "CONTAINER_IP=$IP"
export SPARK_LOCAL_IP=$IP
export SPARK_PUBLIC_DNS=$IP

# Avoid the default Docker behavior of mapping our IP address to an unreachable host name
umount /etc/hosts

if [ "x$1" = "xmaster" ];
then
    /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -i $IP
elif [ "x$1" = "xworker" ];
then
    /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker $2
else
    echo "Usage Error"
fi
